services:
  api:
    image: api-test
    container_name: fast-api
    build:
      context: ./project
    env_file:
      - ./project/.env
    ports:
      - "8000:8000"
    volumes:
      - ./project/config:/code/config
      - ./project/db:/code/db
      - ./project/dependencies:/code/dependencies
      - ./project/models:/code/models
      - ./project/routers:/code/routers
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: project_library
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CHANGE_ME}
      POSTGRES_DB: project_library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
