services:
  frontend:
    image: app-test
    container_name: streamlit-app
    build: 
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/src:/code/src
    depends_on:
      - api

  api:
    image: api-test
    container_name: fast-api
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/code/src
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: project_library
      POSTGRES_PASSWORD: project88library**
      POSTGRES_DB: project_library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
